# Generated by Django 5.2.8 on 2025-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmyapp', '0002_alter_project_options_project_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('consulting', 'Consulting'), ('estimate', 'Estimate'), ('plan_design', 'Plan & Design'), ('construction', 'Construction'), ('flooring', 'Flooring Work'), ('painting', 'Painting Work'), ('elevation_3d', '3D Elevation Design'), ('electric', 'Electric Work'), ('interior_work', 'Interior Work'), ('renovation', 'Renovation'), ('interior_design', 'Interior Design'), ('carpentry', 'Carpentry Work')], max_length=32, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
