# Generated by Django 5.2.8 on 2025-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmyapp', '0003_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, e.g., 919876543210', max_length=32)),
                ('whatsapp_template', models.TextField(blank=True, default="Hi, I'm interested in the Plan & Design service. Please share details.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
