# Generated by Django 5.2.8 on 2025-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmyapp', '0004_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Identifier used in code, e.g., plan_design, basic, premium', max_length=32, unique=True)),
                ('label', models.CharField(help_text='Human friendly name shown in admin', max_length=64)),
                ('category', models.CharField(choices=[('service', 'Service'), ('package', 'Package')], max_length=16)),
                ('template', models.TextField(blank=True, help_text='Use placeholders like {service}, {package}, {price}, {slug}, {category}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'label'),
            },
        ),
    ]
