# Generated by Django 5.2.8 on 2025-11-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmyapp', '0005_whatsapptemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppTemplate',
        ),
    ]
